apiVersion: v1
kind: Service
metadata:
    labels:
        service: reverseproxy
    name: reverseproxy
spec:
    ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    selector:
        service: reverseproxy